version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
           # - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/usr/share/nginx/html/
            - ./logs:/var/log/nginx

